/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

//€1 = Y177.31
public class App {
    public Double yenConverter() {
        double exchangeRate = 177.31;
        double euro = 12;
        double yen = euro*exchangeRate;
        return yen;
    }

    public static void main(String[] args) {
        System.out.println(new App().yenConverter());
    }
}
